export const ROUTE_REGISTRATION = "/registration"
export const ROUTE_COURSES = "/courses"
export const ROUTE_EDUCATIONAL_PROGRAMS = "/educationalPrograms"
export const ROUTE_USERS = "/users"
export const ROUTE_TESTS_COLLECTION = "/testsCollection"
export const ROUTE_PROFILE = "/"